// export const backendCategories = [
//   { label: 'All', value: 'All' },
//   { label: 'Cafe', value: 'Cafe' },
//   { label: 'Home Essentials', value: 'HomeEssentials' },
//   { label: 'Toys', value: 'Toys' },
//   { label: 'Fruits & Vegetables', value: 'FruitsVegetables' },
//   { label: 'Electronics', value: 'Electronics' },
//   { label: 'Mobiles', value: 'Mobiles' },
//   { label: 'Beauty', value: 'Beauty' },
//   { label: 'Fashion', value: 'Fashion' },
//   { label: 'Deal Zone', value: 'DealZone' },
//   { label: 'Baby Store', value: 'BabyStore' },
//   { label: 'Atta, Rice, Oil & Dals', value: 'AttaRiceOilDals' },
//   { label: 'Masala & Dry Fruits', value: 'MasalaDryFruits' },
//   { label: 'Zepto Cafe', value: 'ZeptoCafe' },
//   { label: 'Sweet Cravings', value: 'SweetCravings' },
//   { label: 'Toys & Sports', value: 'ToysSports' },
//   { label: 'Apparel & Lifestyle', value: 'ApparelLifestyle' },
//   { label: 'Jewellery & Accessories', value: 'JewelleryAccessories' },
//   { label: 'Frozen Food', value: 'FrozenFood' },
//   { label: 'Ice Creams & More', value: 'IceCreams' },
//   { label: 'Pack Food', value: 'PackFood' },
//   { label: 'Dairy, Bread & Eggs', value: 'DairyBreadEggs' },
//   { label: 'Cold Drinks & Juices', value: 'ColdDrinksJuices' },
//   { label: 'Munchies', value: 'Munchies' },
//   { label: 'Meat, Fish & Eggs', value: 'MeatFishEggs' },
//   { label: 'Breakfast & Sauces', value: 'BreakfastSauces' },
//   { label: 'Tea, Coffee & More', value: 'TeaCoffee' },
//   { label: 'Biscuits & Cookies', value: 'BiscuitsCookies' },
//   { label: 'Makeup', value: 'Makeup' },
//   { label: 'Skincare', value: 'Skincare' },
//   { label: 'Bath & Body', value: 'BathBody' },
//   { label: 'Hair Care', value: 'HairCare' },
//   { label: 'Cleaning Essentials', value: 'CleaningEssentials' },
//   { label: 'Home Needs', value: 'HomeNeeds' },
//   { label: 'Stationery & Books', value: 'StationeryBooks' },
//   { label: 'Kitchen & Dining', value: 'KitchenDining' },
//   { label: 'Electronics & Appliances', value: 'ElectronicsAppliances' },
//   { label: 'Fragrances & Grooming', value: 'FragrancesGrooming' },
//   { label: 'Feminine Hygiene', value: 'FeminineHygiene' },
//   { label: 'Pharmacy & Wellness', value: 'PharmacyWellness' },
//   { label: 'Sexual Wellness', value: 'SexualWellness' },
//   { label: 'Baby Care', value: 'BabyCare' },
//   { label: 'Pet Care', value: 'PetCare' },
//   { label: 'Paan Corner', value: 'PaanCorner' },
// ];

// // Map frontend labels to backend categories
// export const categoryMap = {
//   "All": "All",
//   "Cafe": "Cafe",
//   "Home": "HomeEssentials",
//   "Toys": "Toys",
//   "Fresh": "FruitsVegetables",
//   "Electronics": "Electronics",
//   "Mobiles": "Mobiles",
//   "Beauty": "Beauty",
//   "Fashion": "Fashion",
//   "Deal Zone": "DealZone",
//   "Baby Store": "BabyStore",
//   "Fruits & Vegetable": "FruitsVegetables",
//   "Atta, Rice, Oil & Dals": "AttaRiceOilDals",
//   "Masala & Dry Fruits": "MasalaDryFruits",
//   "Zepto Cafe": "ZeptoCafe",
//   "Sweet Cravings": "SweetCravings",
//   "Toys & Sports": "ToysSports",
//   "Apparel & Lifestyle": "ApparelLifestyle",
//   "Jewellery & Accessories": "JewelleryAccessories",
//   "Frozen Food": "FrozenFood",
//   "Ice Creams & More": "IceCreams",
//   "Pack Food": "PackFood",
//   "Dairy, Bread & Eggs": "DairyBreadEggs",
//   "Cold Drinks & Juices": "ColdDrinksJuices",
//   "Munchies": "Munchies",
//   "Meat, Fish & Eggs": "MeatFishEggs",
//   "Breakfast & Sauces": "BreakfastSauces",
//   "Tea, Coffee & More": "TeaCoffee",
//   "Biscuits & Cookies": "BiscuitsCookies",
//   "Makeup": "Makeup",
//   "Skincare": "Skincare",
//   "Bath & Body": "BathBody",
//   "Hair Care": "HairCare",
//   "Cleaning Essentials": "CleaningEssentials",
//   "Home Needs": "HomeNeeds",
//   "Stationery & Books": "StationeryBooks",
//   "Kitchen & Dining": "KitchenDining",
//   "Electronics & Appliances": "ElectronicsAppliances",
//   "Fragrances & Grooming": "FragrancesGrooming",
//   "Feminine Hygiene": "FeminineHygiene",
//   "Pharmacy & Wellness": "PharmacyWellness",
//   "Sexual Wellness": "SexualWellness",
//   "Baby Care": "BabyCare",
//   "Pet Care": "PetCare",
//   "Paan Corner": "PaanCorner",
// };

// // Define subcategories for each backend category
// export const subcategoriesMap = {
//   "All": [],
//   "Cafe": ["Espresso", "Pastries", "Cold Brew"],
//   "HomeEssentials": ["Cleaning Supplies", "Storage", "Decor"],
//   "Toys": ["Action Figures", "Puzzles", "Educational Toys"],
//   "FruitsVegetables": ["Fruits", "Vegetables", "Organic"],
//   "Electronics": ["Gadgets", "Accessories", "Chargers"],
//   "Mobiles": ["Smartphones", "Cases", "Screen Protectors"],
//   "Beauty": ["Makeup", "Skincare", "Fragrances"],
//   "Fashion": ["Clothing", "Footwear", "Accessories"],
//   "DealZone": ["Daily Deals", "Seasonal Offers", "Clearance"],
//   "BabyStore": ["Diapers", "Clothing", "Toys"],
//   "AttaRiceOilDals": ["Atta", "Rice", "Cooking Oil", "Dals"],
//   "MasalaDryFruits": ["Spices", "Nuts", "Dry Fruits"],
//   "ZeptoCafe": ["Coffee", "Snacks", "Desserts"],
//   "SweetCravings": ["Chocolates", "Candies", "Cakes"],
//   "ToysSports": ["Sports Equipment", "Outdoor Toys", "Indoor Games"],
//   "ApparelLifestyle": ["Casual Wear", "Formal Wear", "Activewear"],
//   "JewelleryAccessories": ["Necklaces", "Earrings", "Watches"],
//   "FrozenFood": ["Frozen Meals", "Frozen Snacks", "Frozen Vegetables"],
//   "IceCreams": ["Ice Cream", "Sorbet", "Gelato"],
//   "PackFood": ["Canned Food", "Instant Noodles", "Pasta"],
//   "DairyBreadEggs": ["Milk", "Bread", "Eggs", "Cheese"],
//   "ColdDrinksJuices": ["Soda", "Juices", "Energy Drinks"],
//   "Munchies": ["Chips", "Popcorn", "Nuts"],
//   "MeatFishEggs": ["Chicken", "Fish", "Eggs"],
//   "BreakfastSauces": ["Cereals", "Jams", "Sauces"],
//   "TeaCoffee": ["Tea", "Coffee", "Health Drinks"],
//   "BiscuitsCookies": ["Cookies", "Biscuits", "Crackers"],
//   "Makeup": ["Lipsticks", "Foundation", "Mascara"],
//   "Skincare": ["Moisturizers", "Cleansers", "Sunscreen"],
//   "BathBody": ["Soaps", "Body Wash", "Lotions"],
//   "HairCare": ["Shampoos", "Conditioners", "Hair Oils"],
//   "CleaningEssentials": ["Detergents", "Disinfectants", "Mops"],
//   "HomeNeeds": ["Bedding", "Decor", "Lighting"],
//   "StationeryBooks": ["Notebooks", "Pens", "Books"],
//   "KitchenDining": ["Cookware", "Tableware", "Utensils"],
//   "ElectronicsAppliances": ["Kitchen Appliances", "Small Appliances", "Gadgets"],
//   "FragrancesGrooming": ["Perfumes", "Deodorants", "Shaving"],
//   "FeminineHygiene": ["Sanitary Pads", "Tampons", "Menstrual Cups"],
//   "PharmacyWellness": ["Medicines", "Supplements", "First Aid"],
//   "SexualWellness": ["Condoms", "Lubricants", "Intimate Care"],
//   "BabyCare": ["Diapers", "Wipes", "Feeding"],
//   "PetCare": ["Pet Food", "Grooming", "Toys"],
//   "PaanCorner": ["Paan", "Mouth Fresheners", "Chewing Gum"]
// };

// export const productMenuCategories = [
//   { name: "Fruits & Vegetable", image: "https://cdn.zeptonow.com/production/cms/category/38047553-95f3-47c6-a1ff-4794e1227d3a.png" },
//   { name: "Atta, Rice, Oil & Dals", image: "https://cdn.zeptonow.com/production/cms/category/dc4a299d-521f-4a64-8205-c5ba8e1d13e3.png" },
//   { name: "Masala & Dry Fruits", image: "https://cdn.zeptonow.com/production/cms/category/8d4d3977-5197-49d9-9867-8a670524e48b.png" },
//   { name: "Zepto Cafe", image: "https://cdn.zeptonow.com/production/cms/category/031c2a24-d40f-4272-8c71-8a566252495e.png" },
//   { name: "Sweet Cravings", image: "https://cdn.zeptonow.com/production/cms/category/ec7b14c6-2640-4165-b3ae-68c09a249ae0.png" },
//   { name: "Toys & Sports", image: "https://cdn.zeptonow.com/production/cms/category/8d4fb022-bae0-432d-92c8-2b12d97ee6cc.png" },
//   { name: "Apparel & Lifestyle", image: "https://cdn.zeptonow.com/production/cms/category/498eea73-358c-42c1-b482-158e80669be9.png" },
//   { name: "Jewellery & Accessories", image: "https://cdn.zeptonow.com/production/cms/category/20d9687b-58a4-4bf7-a561-99198b4d5ca1.png" },
//   { name: "Frozen Food", image: "https://cdn.zeptonow.com/production/cms/category/366e5b7d-2028-4935-b9f1-75bfa085c3d7.png" },
//   { name: "Ice Creams & More", image: "https://cdn.zeptonow.com/production/cms/category/db346f5e-644f-426a-85af-92d707e086ac.png" },
//   { name: "Pack Food", image: "https://cdn.zeptonow.com/production/cms/category/47b3a34d-8f9f-42fe-97a0-4d8350748924.png" },
//   { name: "Dairy, Bread & Eggs", image: "https://cdn.zeptonow.com/production/cms/category/474e6e58-1894-4378-86f1-168cc7266d1a.png" },
//   { name: "Cold Drinks & Juices", image: "https://cdn.zeptonow.com/production/cms/category/59d2c0cc-e776-407c-9142-7e69898d9eab.png" },
//   { name: "Munchies", image: "https://cdn.zeptonow.com/production/cms/category/90b2faee-1461-465a-a8c6-8c84716dd7dc.png" },
//   { name: "Meat, Fish & Eggs", image: "https://cdn.zeptonow.com/production/cms/category/1237afd6-40bf-4942-a266-25f23025e86c.png" },
//   { name: "Breakfast & Sauces", image: "https://cdn.zeptonow.com/production/cms/category/ab241d87-da5b-4830-b38f-1a6cd30d0d41.png" },
//   { name: "Tea, Coffee & More", image: "https://cdn.zeptonow.com/production/cms/category/92493ad5-6242-42f9-b951-dca41e55d744.png" },
//   { name: "Biscuits & Cookies", image: "https://cdn.zeptonow.com/production/cms/category/9b88fff5-73f5-46fd-999f-1622db4203d7.png" },
//   { name: "Makeup", image: "https://cdn.zeptonow.com/production/cms/category/d1127e88-d743-457a-a588-489267297de4.png" },
//   { name: "Skincare", image: "https://cdn.zeptonow.com/production/cms/category/b1909dfd-726c-412b-beb7-9553bc909363.png" },
//   { name: "Bath & Body", image: "https://cdn.zeptonow.com/production/cms/category/e4fe52ef-96d9-4289-afb1-1c1ca7efd85b.png" },
//   { name: "Hair Care", image: "https://cdn.zeptonow.com/production/cms/category/eb6fe22a-f8b8-4189-8d9a-deb32ff659c9.png" },
//   { name: "Cleaning Essentials", image: "https://cdn.zeptonow.com/production/cms/category/acfa1279-d46b-408c-8f74-6fcd71bd89f9.png" },
//   { name: "Home Needs", image: "https://cdn.zeptonow.com/production/cms/category/b322b3db-e75e-45e5-a11d-7ee37561c426.png" },
//   { name: "Stationery & Books", image: "https://cdn.zeptonow.com/production/cms/category/b5cfc944-9611-4f08-b4f9-a071d07b1aad.png" },
//   { name: "Kitchen & Dining", image: "https://cdn.zeptonow.com/production/cms/category/c42610fc-a94c-40f6-9e74-d30c4a1f5895.png" },
//   { name: "Electronics & Appliances", image: "https://cdn.zeptonow.com/production/cms/category/c084c75c-82ca-497f-857c-5069c6723194.png" },
//   { name: "Fragrances & Grooming", image: "https://cdn.zeptonow.com/production/cms/category/a4d7f18e-3a58-4c85-b912-f15f0be533ab.png" },
//   { name: "Feminine Hygiene", image: "https://cdn.zeptonow.com/production/cms/category/2b267097-f22b-4269-be34-1ea534ced3d4.png" },
//   { name: "Pharmacy & Wellness", image: "https://cdn.zeptonow.com/production/cms/category/bc5f6b57-fa3a-4a71-b498-7b8cb83323f9.png" },
//   { name: "Sexual Wellness", image: "https://cdn.zeptonow.com/production/cms/category/f4371151-d6ed-42d6-9338-8f7391d03fec.png" },
//   { name: "Baby Care", image: "https://cdn.zeptonow.com/production/cms/category/227b70d5-d1cf-428b-a276-1392c5067eb3.png" },
//   { name: "Pet Care", image: "https://cdn.zeptonow.com/production/cms/category/b117aaf8-960c-43c2-83e8-76d6d238c510.png" },
//   { name: "Paan Corner", image: "https://cdn.zeptonow.com/production/cms/category/6d26710a-1dd8-4d53-9884-33bbaebc4bf4.png" },
// ];

export const backendCategories = [
  { label: 'All', value: 'All' },
  { label: 'Cafe', value: 'Cafe' },
  { label: 'Home Essentials', value: 'HomeEssentials' },
  { label: 'Toys', value: 'Toys' },
  { label: 'Fruits & Vegetables', value: 'FruitsVegetables' },
  { label: 'Electronics', value: 'Electronics' },
  { label: 'Mobiles', value: 'Mobiles' },
  { label: 'Beauty', value: 'Beauty' },
  { label: 'Fashion', value: 'Fashion' },
  { label: 'Deal Zone', value: 'DealZone' },
  { label: 'Baby Store', value: 'BabyStore' },
  { label: 'Atta, Rice, Oil & Dals', value: 'AttaRiceOilDals' },
  { label: 'Masala & Dry Fruits', value: 'MasalaDryFruits' },
  { label: 'Zepto Cafe', value: 'ZeptoCafe' },
  { label: 'Sweet Cravings', value: 'SweetCravings' },
  { label: 'Toys & Sports', value: 'ToysSports' },
  { label: 'Apparel & Lifestyle', value: 'ApparelLifestyle' },
  { label: 'Jewellery & Accessories', value: 'JewelleryAccessories' },
  { label: 'Frozen Food', value: 'FrozenFood' },
  { label: 'Ice Creams & More', value: 'IceCreams' },
  { label: 'Pack Food', value: 'PackFood' },
  { label: 'Dairy, Bread & Eggs', value: 'DairyBreadEggs' },
  { label: 'Cold Drinks & Juices', value: 'ColdDrinksJuices' },
  { label: 'Munchies', value: 'Munchies' },
  { label: 'Meat, Fish & Eggs', value: 'MeatFishEggs' },
  { label: 'Breakfast & Sauces', value: 'BreakfastSauces' },
  { label: 'Tea, Coffee & More', value: 'TeaCoffee' },
  { label: 'Biscuits & Cookies', value: 'BiscuitsCookies' },
  { label: 'Makeup', value: 'Makeup' },
  { label: 'Skincare', value: 'Skincare' },
  { label: 'Bath & Body', value: 'BathBody' },
  { label: 'Hair Care', value: 'HairCare' },
  { label: 'Cleaning Essentials', value: 'CleaningEssentials' },
  { label: 'Home Needs', value: 'HomeNeeds' },
  { label: 'Stationery & Books', value: 'StationeryBooks' },
  { label: 'Kitchen & Dining', value: 'KitchenDining' },
  { label: 'Electronics & Appliances', value: 'ElectronicsAppliances' },
  { label: 'Fragrances & Grooming', value: 'FragrancesGrooming' },
  { label: 'Feminine Hygiene', value: 'FeminineHygiene' },
  { label: 'Pharmacy & Wellness', value: 'PharmacyWellness' },
  { label: 'Sexual Wellness', value: 'SexualWellness' },
  { label: 'Baby Care', value: 'BabyCare' },
  { label: 'Pet Care', value: 'PetCare' },
  { label: 'Paan Corner', value: 'PaanCorner' },
];

// Map frontend labels to backend categories
export const categoryMap = {
  "All": "All",
  "Cafe": "Cafe",
  "Home": "HomeEssentials",
  "Toys": "Toys",
  "Fresh": "FruitsVegetables",
  "Electronics": "Electronics",
  "Mobiles": "Mobiles",
  "Beauty": "Beauty",
  "Fashion": "Fashion",
  "Deal Zone": "DealZone",
  "Baby Store": "BabyStore",
  "Fruits & Vegetable": "FruitsVegetables",
  "Atta, Rice, Oil & Dals": "AttaRiceOilDals",
  "Masala & Dry Fruits": "MasalaDryFruits",
  "Zepto Cafe": "ZeptoCafe",
  "Sweet Cravings": "SweetCravings",
  "Toys & Sports": "ToysSports",
  "Apparel & Lifestyle": "ApparelLifestyle",
  "Jewellery & Accessories": "JewelleryAccessories",
  "Frozen Food": "FrozenFood",
  "Ice Creams & More": "IceCreams",
  "Pack Food": "PackFood",
  "Dairy, Bread & Eggs": "DairyBreadEggs",
  "Cold Drinks & Juices": "ColdDrinksJuices",
  "Munchies": "Munchies",
  "Meat, Fish & Eggs": "MeatFishEggs",
  "Breakfast & Sauces": "BreakfastSauces",
  "Tea, Coffee & More": "TeaCoffee",
  "Biscuits & Cookies": "BiscuitsCookies",
  "Makeup": "Makeup",
  "Skincare": "Skincare",
  "Bath & Body": "BathBody",
  "Hair Care": "HairCare",
  "Cleaning Essentials": "CleaningEssentials",
  "Home Needs": "HomeNeeds",
  "Stationery & Books": "StationeryBooks",
  "Kitchen & Dining": "KitchenDining",
  "Electronics & Appliances": "ElectronicsAppliances",
  "Fragrances & Grooming": "FragrancesGrooming",
  "Feminine Hygiene": "FeminineHygiene",
  "Pharmacy & Wellness": "PharmacyWellness",
  "Sexual Wellness": "SexualWellness",
  "Baby Care": "BabyCare",
  "Pet Care": "PetCare",
  "Paan Corner": "PaanCorner",
};

export const productMenuCategories = [
  { name: "Fruits & Vegetable", image: "https://cdn.zeptonow.com/production/cms/category/38047553-95f3-47c6-a1ff-4794e1227d3a.png" },
  { name: "Atta, Rice, Oil & Dals", image: "https://cdn.zeptonow.com/production/cms/category/dc4a299d-521f-4a64-8205-c5ba8e1d13e3.png" },
  { name: "Masala & Dry Fruits", image: "https://cdn.zeptonow.com/production/cms/category/8d4d3977-5197-49d9-9867-8a670524e48b.png" },
  { name: "Zepto Cafe", image: "https://cdn.zeptonow.com/production/cms/category/031c2a24-d40f-4272-8c71-8a566252495e.png" },
  { name: "Sweet Cravings", image: "https://cdn.zeptonow.com/production/cms/category/ec7b14c6-2640-4165-b3ae-68c09a249ae0.png" },
  { name: "Toys & Sports", image: "https://cdn.zeptonow.com/production/cms/category/8d4fb022-bae0-432d-92c8-2b12d97ee6cc.png" },
  { name: "Apparel & Lifestyle", image: "https://cdn.zeptonow.com/production/cms/category/498eea73-358c-42c1-b482-158e80669be9.png" },
  { name: "Jewellery & Accessories", image: "https://cdn.zeptonow.com/production/cms/category/20d9687b-58a4-4bf7-a561-99198b4d5ca1.png" },
  { name: "Frozen Food", image: "https://cdn.zeptonow.com/production/cms/category/366e5b7d-2028-4935-b9f1-75bfa085c3d7.png" },
  { name: "Ice Creams & More", image: "https://cdn.zeptonow.com/production/cms/category/db346f5e-644f-426a-85af-92d707e086ac.png" },
  { name: "Pack Food", image: "https://cdn.zeptonow.com/production/cms/category/47b3a34d-8f9f-42fe-97a0-4d8350748924.png" },
  { name: "Dairy, Bread & Eggs", image: "https://cdn.zeptonow.com/production/cms/category/474e6e58-1894-4378-86f1-168cc7266d1a.png" },
  { name: "Cold Drinks & Juices", image: "https://cdn.zeptonow.com/production/cms/category/59d2c0cc-e776-407c-9142-7e69898d9eab.png" },
  { name: "Munchies", image: "https://cdn.zeptonow.com/production/cms/category/90b2faee-1461-465a-a8c6-8c84716dd7dc.png" },
  { name: "Meat, Fish & Eggs", image: "https://cdn.zeptonow.com/production/cms/category/1237afd6-40bf-4942-a266-25f23025e86c.png" },
  { name: "Breakfast & Sauces", image: "https://cdn.zeptonow.com/production/cms/category/ab241d87-da5b-4830-b38f-1a6cd30d0d41.png" },
  { name: "Tea, Coffee & More", image: "https://cdn.zeptonow.com/production/cms/category/92493ad5-6242-42f9-b951-dca41e55d744.png" },
  { name: "Biscuits & Cookies", image: "https://cdn.zeptonow.com/production/cms/category/9b88fff5-73f5-46fd-999f-1622db4203d7.png" },
  { name: "Makeup", image: "https://cdn.zeptonow.com/production/cms/category/d1127e88-d743-457a-a588-489267297de4.png" },
  { name: "Skincare", image: "https://cdn.zeptonow.com/production/cms/category/b1909dfd-726c-412b-beb7-9553bc909363.png" },
  { name: "Bath & Body", image: "https://cdn.zeptonow.com/production/cms/category/e4fe52ef-96d9-4289-afb1-1c1ca7efd85b.png" },
  { name: "Hair Care", image: "https://cdn.zeptonow.com/production/cms/category/eb6fe22a-f8b8-4189-8d9a-deb32ff659c9.png" },
  { name: "Cleaning Essentials", image: "https://cdn.zeptonow.com/production/cms/category/acfa1279-d46b-408c-8f74-6fcd71bd89f9.png" },
  { name: "Home Needs", image: "https://cdn.zeptonow.com/production/cms/category/b322b3db-e75e-45e5-a11d-7ee37561c426.png" },
  { name: "Stationery & Books", image: "https://cdn.zeptonow.com/production/cms/category/b5cfc944-9611-4f08-b4f9-a071d07b1aad.png" },
  { name: "Kitchen & Dining", image: "https://cdn.zeptonow.com/production/cms/category/c42610fc-a94c-40f6-9e74-d30c4a1f5895.png" },
  { name: "Electronics & Appliances", image: "https://cdn.zeptonow.com/production/cms/category/c084c75c-82ca-497f-857c-5069c6723194.png" },
  { name: "Fragrances & Grooming", image: "https://cdn.zeptonow.com/production/cms/category/a4d7f18e-3a58-4c85-b912-f15f0be533ab.png" },
  { name: "Feminine Hygiene", image: "https://cdn.zeptonow.com/production/cms/category/2b267097-f22b-4269-be34-1ea534ced3d4.png" },
  { name: "Pharmacy & Wellness", image: "https://cdn.zeptonow.com/production/cms/category/bc5f6b57-fa3a-4a71-b498-7b8cb83323f9.png" },
  { name: "Sexual Wellness", image: "https://cdn.zeptonow.com/production/cms/category/f4371151-d6ed-42d6-9338-8f7391d03fec.png" },
  { name: "Baby Care", image: "https://cdn.zeptonow.com/production/cms/category/227b70d5-d1cf-428b-a276-1392c5067eb3.png" },
  { name: "Pet Care", image: "https://cdn.zeptonow.com/production/cms/category/b117aaf8-960c-43c2-83e8-76d6d238c510.png" },
  { name: "Paan Corner", image: "https://cdn.zeptonow.com/production/cms/category/6d26710a-1dd8-4d53-9884-33bbaebc4bf4.png" },
];